server:
  port: 8088
  servlet:
    context-path: /orange
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/orange?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    elasticsearch:
      cluster-name: escluster
      cluster-nodes: 127.0.0.1:9300
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 894660619@qq.com #QQ邮箱
    password: cwvrzcidgindbbjd #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: orange #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: 894660619@qq.com #与上面的username保持一致
logging:
  level:
    com.style.orange: debug
